version: '3.1'

services:

  server:
    build: ./server
    command: npm start
    container_name: kitchen-buddy-server
    ports: 
      - 8000:8000
    env_file: 
      - .env
    volumes:
      - ./server:/usr/src/app


  mongo:
    image: mongo:4.4.6
    container_name: kitchen-buddy-mongo
    restart: always
    env_file: 
      - .env
    volumes:
      - default:/data/db


networks: 
  default:
    name: kitchen-buddy-network

volumes:
  default:
    name: kitchen-buddy-volume
